### ISSUE TITLE
Duplicate PhaseCodeKind value in espiDerived.xsd

### ISSUE THREAD

**Issue by AndrewJo** [energyos/OpenESPI-Common-java#252]
In https://github.com/energyos/OpenESPI-Common-java/blob/master/etc/espiDerived.xsd#L2914-L2925, enumeration for phases A, C, and neutral is set to value `97` but that also happens to be the enumeration value for BC to neutral.

Is this intentional (e.g. `AC to N == BC to N`) or was this meant to be a different value?

**Comment by MartyBurns** [comment]
resolved #f9b39a42d58c7762f388cd79b6fc33095ac0d9d8
